import { Box, Button, Flex, Link, Text } from "@chakra-ui/react";
import { Formik, Form } from "formik";
import { withUrqlClient } from "next-urql";
import { useRouter } from "next/router";
import React from "react";
import { InputField } from "../components/InputField";
import Wrapper from "../components/Wrapper";
import {
  useForgotPasswordMutation,
  useLoginMutation,
} from "../generated/graphql";
import { createUrqlClient } from "../utils/createUrqlClient";
import { toErrorMap } from "../utils/toErrorMap";
import { Toast, successToast } from "../components/Toast";

const ForgotPassword: React.FC<{}> = ({}) => {
  const [, forgotPassword] = useForgotPasswordMutation(); // custom hook created by code generator to make sure that the response is not of type any
  const router = useRouter();
  // the code generated by code generator is thene in src/generated
  const handleSubmit = async (email: string) => {
    await forgotPassword({ email });
    successToast("email sent : )");
  };
  return (
    <Wrapper variant="small">
      <Formik
        initialValues={{ email: "" }}
        onSubmit={({ email }) => handleSubmit(email)}
      >
        {({ values, handleChange, isSubmitting }) => (
          <Form>
            <Toast />
            <InputField
              name="email"
              placeholder="enter your registered email"
              label="Email"
              type="text"
            />
            <Button
              mt={4}
              colorScheme="teal"
              size="md"
              type="submit"
              isLoading={isSubmitting}
            >
              Send Email
            </Button>
          </Form>
        )}
      </Formik>
    </Wrapper>
  );
};

export default withUrqlClient(createUrqlClient)(ForgotPassword);
