import Wrapper from "../components/Wrapper";
import { Box, Button } from "@chakra-ui/react";
import { Formik, Form } from "formik";
import { InputField } from "../components/InputField";
import { useLoginMutation } from "../generated/graphql";
import { Toast, errorToast, successToast } from "../components/Toast";
import { useRouter } from "next/router";
interface registerProps {}

type loginValues = {
  email: string;
  password: string;
};

const Login: React.FC<registerProps> = ({}) => {
  const [, register] = useLoginMutation(); // custom hook created by code generator to make sure that the response is not of type any
  const router = useRouter();
  // the code generated by code generator is thene in src/generated
  const handleSubmit = async (values: loginValues, setErrors: any) => {
    const response = await register(values);
    if (!response.error && response.data.login) {
      router.push("/");
    } else {
      setErrors({
        email: "wrong email / wrong password",
        password: "wrong email / wrong password",
      });
      errorToast("invalid credentials : ( ");
    }
  };
  return (
    <Wrapper variant="small">
      <Toast />
      <Formik
        initialValues={{ email: "", password: "" }}
        onSubmit={(values, { setErrors }) => handleSubmit(values, setErrors)}
      >
        {({ values, handleChange, isSubmitting }) => (
          <Form>
            <InputField
              name="email"
              placeholder="email"
              label="email"
              type="email"
            />
            <Box mt={4}>
              <InputField
                name="password"
                placeholder="password"
                label="Password"
                type="password"
              />
            </Box>
            <Button
              mt={4}
              colorScheme="teal"
              size="md"
              type="submit"
              isLoading={isSubmitting}
            >
              Register
            </Button>
          </Form>
        )}
      </Formik>
    </Wrapper>
  );
};

export default Login;
